version: "3"
services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    build: .
    restart: always
    environment:
      - SECRET_KEY
      - DEBUG=False
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - web-django:/Django
      - web-static:/Django/static
    env_file:
      - ./.env
    command: "gunicorn --bind :8000 JoogleDataLabeling.wsgi:application"
    expose:
      - "8000"
    volumes:
    - django:/Django
    - /sys:/sys
    depends_on:
    - postgres

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

volumes:
  pgdata:
  django:
  web-django:
  web-static: