# Generated by Django 2.2.3 on 2019-07-08 22:12

from django.db import migrations
import os
import json

def import_data(apps, schema_editor):
    Content = apps.get_model('labeling', 'Content')

    for filename in os.listdir("urteile"):
        with open(os.path.join("urteile/", filename), encoding='utf-8') as json_file:
            d = json.load(json_file)
            for absatz in d['absaetze']:
                print(absatz['text'], d['aktenzeichen'])
                c = Content(content=absatz['text'], meta_data=absatz['num'] + '#' + d['aktenzeichen'])
                c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_data),

    ]
